name: Issues Helper

on:
  issues:
    types: [opened]

jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: new issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ secrets.ACTION_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 @${{ github.event.issue.user.login }}，我已收到你的issue，问题有新的进展或疑问我会及时回复你。
